### ISSUE TITLE
Payment URI Alphanumeric Mode

### ISSUE THREAD

**Issue by jonas-lundqvist** [bitjson/chip-paypro#5]
Should this be included in the spec or not?

Pros:
* Allows better (denser) QR codes.
* Easy to implement.
* Very little drawbacks for wallets to implement the parsing.

Cons:
* Can not be reliably used for sharing QR codes for a very long time (if ever) until a big majority of BCH wallets supports it.
* Introducing "another address" is a UX nightmare. If a user wants to receive something (anything) the goal should be to only present one text address/QR code.

While I originally was supportive of this idea I wonder how big problem this actually solves. Mobile cameras that scans QR codes are very good at it, even on cheap devices and I fear that this will be something some wallets implement but it isn't used anywhere. My feeling is that the old way is "good enough".

I'm on the fence and so are probably others, so please list more pros and cons.

**Comment by bitjson** [comment]
In digging through my now-ancient notes from the past decade and reviewing old mailing list archives for https://github.com/bitjson/chip-paypro/issues/6#issuecomment-1594039604, my opinion on this kind of issue solidified a bit more: 

> The best time to plant this tree was 11 years ago, the second best time is now. It's fine if it's not 100% reliable for a few years. 

The implementation is trivial, and the only thing needed for widespread support is one major wallet or service provider to say, "We don't care about dead wallet projects, we're doing this." The dead projects will upgrade or be abandoned. No money is at risk here, just minor inconvenience among users who haven't actually used P2P cash in years and haven't yet upgraded to a modern wallet.

**Comment by bitjson** [comment]
Oh, and as mentioned in #6:

> We also have a rare opportunity to fix this issue with nearly complete coverage in new clients (which might implement support at the same time as the token related changes)

I'm going to close this issue for now, but if anyone feels very strongly about it, please leave a comment and we can re-open.
